---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Disable checks of excessive copy-pastes
  - SPELL # Disable checks of spelling mistakes
# Disable the DevSkim linter for now because it is raising false positives
# and there is not a way to specify for the linter to ignore certain lines or certain files: REPOSITORY_DEVSKIM
# https://github.com/microsoft/DevSkim
DISABLE_LINTERS:
  [
    JAVASCRIPT_STANDARD,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    REPOSITORY_DEVSKIM,
    REPOSITORY_GITLEAKS,
    TERRAFORM_CHECKOV,
  ]
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
# Exclude certain files from linting
# yamllint disable-line rule:line-length
FILTER_REGEX_EXCLUDE: "(CHANGELOG.md)"
GROOVY_NPM_GROOVY_LINT_ARGUMENTS: ["--failon", "error"]
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(tests/resources/example_de.json)"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(tests/cassettes/.*.yml)"
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(tests/cassettes/.*.yml)"
